### ISSUE TITLE
Issue installing on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by HarryEm** [bnels/BATS.py#1]
Hi,

When I run 

`git clone --recursive git@github.com:bnels/BATS.py.git`

I get the message

Cloning into 'BATS.py'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

And when I try to install from the github link

`git clone --recursive https://github.com/bnels/BATS.py.git`

It fails to install the submodules:

Submodule 'BATS_include' (git@github.com:bnels/BATS.git) registered for path 'BATS_include'
Submodule 'pybind11' (git@github.com:pybind/pybind11.git) registered for path 'pybind11'
Cloning into '/home/harryem/BATS.py/BATS_include'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Thanks,

Harry

**Comment by bnels** [comment]
Hi Harry,

I think this is because you haven't set up ssh keys for github.  See [here](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for how to generate ssh keys, and [here](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) for how to add them to your github account.

Alternatively, you can try using https protocol e.g.

```bash
git clone --recursive https://github.com/bnels/BATS.py.git
```

I recommend setting up an ssh key if it is an option.

Let me know if you're still having issues.

**Comment by HarryEm** [comment]
Great, thanks Brad, all working now.

Harry
